/**
 * Save resume and cover letter text generated by SeleniumBase.
 * Reads one JSON object from stdin: { "jobId": number, "resumeText": string, "coverLetterText": string }
 *
 * Usage: echo '{"jobId":1,"resumeText":"...","coverLetterText":"..."}' | npx tsx scripts/saveGeneratedDocsFromSelenium.ts
 */

import "dotenv/config";
import { saveGeneratedDocumentsOnly } from "../lib/generateDocuments";
import { prisma } from "../lib/prisma";

async function main() {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) chunks.push(chunk as Buffer);
  const raw = Buffer.concat(chunks).toString("utf-8").trim();
  const data = JSON.parse(raw || "{}") as { jobId: number; resumeText: string; coverLetterText: string };
  const { jobId, resumeText, coverLetterText } = data;
  if (!jobId || typeof resumeText !== "string" || typeof coverLetterText !== "string") {
    throw new Error("Invalid input: need jobId, resumeText, coverLetterText");
  }
  await saveGeneratedDocumentsOnly(jobId, resumeText, coverLetterText);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
